services:
  - type: web
    name: inventario-backend
    env: node
    plan: free
    rootDir: inventario
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: ep-floral-scene-apl9l0t0-pooler.c-7.us-east-1.aws.neon.tech
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: neondb
      - key: DB_PORT
        value: "5432"
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: inventario-frontend
    env: static
    plan: free
    rootDir: frontend-productos
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false
